function createfigure(X1, ymatrix1)
%CREATEFIGURE(X1, ymatrix1)
%  X1:  stairs x
%  YMATRIX1:  stairs matrix data

%  Auto-generated by MATLAB on 14-Jan-2021 20:48:48

% Create figure
figure;

% Create axes
axes1 = axes('Position',[0.0695652173913043 0.110179640718563 0.912374581939799 0.868263473053892]);
hold(axes1,'on');
colororder([1 0 0;0 0.447058823529412 0.741176470588235;1 0.074509803921569 0.650980392156863;0 1 0;0 1 1;0.301960784313725 0.745098039215686 0.933333333333333;0.635294117647059 0.07843137254902 0.184313725490196]);

% Create multiple lines using matrix input to stairs
stairs1 = stairs(X1,ymatrix1,'LineWidth',2);
set(stairs1(1),'DisplayName','DNA_0','Color',[0 0.447058823529412 0.741176470588235]);
set(stairs1(2),'DisplayName','DNA_{0\_BAD}','Color',[1 0.411764705882353 0.16078431372549]);
set(stairs1(3),'DisplayName','mRNA_{flp}');
set(stairs1(4),'DisplayName','Flp');
set(stairs1(5),'DisplayName','DNA_{1\_BAD}','Color',[0.47843137254902 0.690196078431373 0.082352941176471]);

% Create ylabel
ylabel('molecules');

% Create xlabel
xlabel('time (s)');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 28800]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',24,'GridAlpha',0.5,'LineStyleOrder',{'-'},'XGrid','on','XMinorGrid','on','XMinorTick','on','YScale','log','XScale','log','YGrid','on','YMinorGrid',...
    'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.172697682752031 0.59761081974902 0.101003344481605 0.227803738317757],'LineWidth',1,'FontSize',24,'FontName','Helvetica Neue');

